-- Insert Periods
INSERT INTO periods (id, name, range, description) VALUES ('han', '汉代', '公元前202年 - 公元220年', '张骞凿空西域，丝绸之路正式开通。') ON CONFLICT (id) DO NOTHING;
INSERT INTO periods (id, name, range, description) VALUES ('tang', '唐代', '公元618年 - 公元907年', '丝绸之路发展到鼎盛时期，东西方文化交流繁荣。') ON CONFLICT (id) DO NOTHING;
INSERT INTO periods (id, name, range, description) VALUES ('mongol', '蒙元时期', '公元1206年 - 公元1368年', '蒙古帝国打通了亚欧大陆，海上丝路也空前繁荣。') ON CONFLICT (id) DO NOTHING;

-- Insert Sources
INSERT INTO sources (id, title, author, url, description) VALUES ('s1', '《史记·大宛列传》', '司马迁', NULL, '记载了张骞出使西域的见闻。') ON CONFLICT (id) DO NOTHING;
INSERT INTO sources (id, title, author, url, description) VALUES ('s2', '《大唐西域记》', '玄奘', NULL, '记录了唐代西域及印度的地理与风土人情。') ON CONFLICT (id) DO NOTHING;
INSERT INTO sources (id, title, author, url, description) VALUES ('s3', '《马可·波罗游记》', '马可·波罗', NULL, '详细记载了蒙元时期的中国及沿途所见所闻。') ON CONFLICT (id) DO NOTHING;
INSERT INTO sources (id, title, author, url, description) VALUES ('s4', '《诸蕃志》', '赵汝适', NULL, '记载了宋代海上丝绸之路沿线各国的风土人情和物产。') ON CONFLICT (id) DO NOTHING;
INSERT INTO sources (id, title, author, url, description) VALUES ('s5', '《岛夷志略》', '汪大渊', NULL, '元代航海家亲历数十国后写成的纪实著作。') ON CONFLICT (id) DO NOTHING;

-- Insert Places
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_changan', '长安', ARRAY['西安', 'Chang''an', 'Xi''an']::TEXT[], '丝绸之路的东端起点，汉唐两代的政治、经济和文化中心。', 'capital', 'high', 108.9398, 34.3416, ARRAY['han', 'tang']::TEXT[], '[{"period_id":"han","note":"汉朝首都，张骞出使西域的出发地。"},{"period_id":"tang","note":"世界第一大都会，万国来朝的国际性都城。"}]'::jsonb, 'confirmed', ARRAY['p_dunhuang', 'p_hangzhou']::TEXT[], ARRAY['s1', 's2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_dunhuang', '敦煌', ARRAY['沙州', 'Dunhuang']::TEXT[], '河西走廊的最西端，丝路上的重要咽喉和佛教艺术宝库。', 'oasis', 'high', 94.6618, 40.1421, ARRAY['han', 'tang', 'mongol']::TEXT[], '[{"period_id":"han","note":"设敦煌郡，扼守玉门关和阳关。"},{"period_id":"tang","note":"莫高窟壁画艺术达到顶峰。"}]'::jsonb, 'confirmed', ARRAY['p_changan', 'p_turpan', 'p_kashgar', 'p_loulan']::TEXT[], ARRAY['s1', 's2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_turpan', '吐鲁番', ARRAY['高昌', '交河', 'Turpan']::TEXT[], '天山南麓的重要绿洲城市，历代均为西域政治、经济与文化重镇。', 'oasis', 'medium', 89.1841, 42.9476, ARRAY['han', 'tang', 'mongol']::TEXT[], '[{"period_id":"tang","note":"唐朝在此设安西都护府，辖理西域。"}]'::jsonb, 'confirmed', ARRAY['p_dunhuang', 'p_kuqa']::TEXT[], ARRAY['s2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_loulan', '楼兰', ARRAY['鄯善', 'Loulan']::TEXT[], '罗布泊西岸的古代西域重镇，汉代丝绸之路必经之地，后因环境恶化被废弃。', 'ruin', 'medium', 89.9142, 40.5186, ARRAY['han']::TEXT[], '[{"period_id":"han","note":"丝绸之路上著名的王国，曾为中原王朝与匈奴必争之地。"}]'::jsonb, 'confirmed', ARRAY['p_dunhuang', 'p_khotan']::TEXT[], ARRAY['s1']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_kuqa', '库车', ARRAY['龟兹', 'Kuqa']::TEXT[], '塔里木盆地北缘重镇，古代龟兹国所在地，音乐和佛教文化极其发达。', 'oasis', 'high', 82.9664, 41.7196, ARRAY['han', 'tang']::TEXT[], '[{"period_id":"tang","note":"安西四镇之一，名僧鸠摩罗什的故乡。"}]'::jsonb, 'confirmed', ARRAY['p_turpan', 'p_kashgar']::TEXT[], ARRAY['s2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_khotan', '和田', ARRAY['于阗', 'Khotan']::TEXT[], '塔里木盆地南缘的绿洲王国，以盛产美玉和丝织品闻名。', 'oasis', 'high', 79.9222, 37.1122, ARRAY['han', 'tang', 'mongol']::TEXT[], '[{"period_id":"tang","note":"安西四镇之一，著名的佛教文化中心。"},{"period_id":"mongol","note":"马可波罗称其居民多经营手工业和商业。"}]'::jsonb, 'confirmed', ARRAY['p_loulan', 'p_kashgar']::TEXT[], ARRAY['s2', 's3']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_kashgar', '喀什', ARRAY['疏勒', 'Kashgar']::TEXT[], '塔里木盆地西缘的重镇，南北两道在此交汇，通往中亚的必经之路。', 'oasis', 'high', 75.9897, 39.4677, ARRAY['han', 'tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_khotan', 'p_kuqa', 'p_samarkand']::TEXT[], ARRAY['s1', 's2', 's3']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_samarkand', '撒马尔罕', ARRAY['康国', 'Samarkand']::TEXT[], '中亚粟特人的中心，连接东西方贸易的核心枢纽。', 'capital', 'high', 66.9749, 39.6542, ARRAY['han', 'tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_kashgar', 'p_merv']::TEXT[], ARRAY['s2', 's3']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_merv', '马雷', ARRAY['木鹿', 'Merv']::TEXT[], '古代呼罗珊地区的重要城市，丝路上的大都会，曾是世界上人口最多的城市之一。', 'capital', 'medium', 62.1833, 37.6667, ARRAY['han', 'tang', 'mongol']::TEXT[], '[{"period_id":"tang","note":"阿拉伯帝国向东扩张的重要据点。"},{"period_id":"mongol","note":"被蒙古军队彻底摧毁，失去昔日辉煌。"}]'::jsonb, 'confirmed', ARRAY['p_samarkand', 'p_baghdad']::TEXT[], ARRAY['s2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_baghdad', '巴格达', ARRAY['Baghdad']::TEXT[], '阿拔斯王朝首都，东西方文化交流的熔炉，极度繁华。', 'capital', 'high', 44.3661, 33.3152, ARRAY['tang', 'mongol']::TEXT[], '[{"period_id":"tang","note":"当时世界上最繁华的城市之一，阿拉伯帝国中心。"}]'::jsonb, 'confirmed', ARRAY['p_merv', 'p_damascus']::TEXT[], ARRAY['s2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_damascus', '大马士革', ARRAY['Damascus']::TEXT[], '位于叙利亚，世界上最古老的持续有人居住的城市之一。', 'capital', 'medium', 36.2913, 33.5138, ARRAY['han', 'tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_baghdad', 'p_antioch', 'p_palmyra']::TEXT[], ARRAY[]::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_palmyra', '帕尔米拉', ARRAY['Palmyra']::TEXT[], '叙利亚沙漠中的绿洲城市，沟通波斯与罗马帝国贸易的桥梁。', 'ruin', 'medium', 38.2678, 34.5539, ARRAY['han']::TEXT[], NULL, 'confirmed', ARRAY['p_damascus', 'p_antioch']::TEXT[], ARRAY[]::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_antioch', '安条克', ARRAY['Antioch']::TEXT[], '地中海东岸的重镇，丝绸运往欧洲的集散地。', 'capital', 'high', 36.1601, 36.2023, ARRAY['han', 'tang']::TEXT[], NULL, 'confirmed', ARRAY['p_palmyra', 'p_constantinople', 'p_rome']::TEXT[], ARRAY[]::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_constantinople', '君士坦丁堡', ARRAY['拂菻', '伊斯坦布尔', 'Constantinople', 'Istanbul']::TEXT[], '拜占庭帝国首都，沟通欧亚大陆的桥梁。', 'capital', 'high', 28.9784, 41.0082, ARRAY['tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_antioch', 'p_rome']::TEXT[], ARRAY['s2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_rome', '罗马', ARRAY['大秦', 'Rome']::TEXT[], '罗马帝国首都，古代丝绸之路的西端终点之一。', 'capital', 'high', 12.4964, 41.9028, ARRAY['han']::TEXT[], '[{"period_id":"han","note":"汉代称之为大秦，对中国丝绸有着极高需求。"}]'::jsonb, 'confirmed', ARRAY['p_antioch']::TEXT[], ARRAY['s1']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_alexandria', '亚历山大', ARRAY['Alexandria']::TEXT[], '埃及的著名海港，连接红海航线与地中海世界。', 'port', 'medium', 29.9187, 31.2001, ARRAY['han', 'tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_aden', 'p_rome']::TEXT[], ARRAY[]::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_aden', '亚丁', ARRAY['阿丹', 'Aden']::TEXT[], '红海与印度洋交汇处的咽喉要道，海上丝路重要中转站。', 'port', 'medium', 44.9782, 12.8023, ARRAY['tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_alexandria', 'p_hormuz', 'p_calicut']::TEXT[], ARRAY['s4', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_hormuz', '霍尔木兹', ARRAY['忽鲁谟斯', 'Hormuz']::TEXT[], '控制波斯湾的重要商业城邦，往来东西方的船只常在此停靠。', 'port', 'medium', 56.4608, 27.0603, ARRAY['mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_aden', 'p_calicut']::TEXT[], ARRAY['s3', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_calicut', '卡利卡特', ARRAY['古里', 'Calicut']::TEXT[], '印度西南海岸繁华的港口，出产大量香料，吸引了众多中国和阿拉伯商人。', 'port', 'high', 75.7804, 11.2588, ARRAY['tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_hormuz', 'p_aden', 'p_malacca']::TEXT[], ARRAY['s4', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_malacca', '马六甲', ARRAY['满剌加', 'Malacca']::TEXT[], '东南亚最重要的海上贸易枢纽之一，扼守马六甲海峡。', 'port', 'high', 102.2501, 2.1896, ARRAY['tang', 'mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_calicut', 'p_guangzhou', 'p_quanzhou']::TEXT[], ARRAY['s4', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_mogadishu', '摩加迪沙', ARRAY['木骨都束', 'Mogadishu']::TEXT[], '东非海岸重要城邦，海上丝绸之路与非洲大陆交流的门户。', 'port', 'low', 45.3182, 2.0469, ARRAY['mongol']::TEXT[], NULL, 'confirmed', ARRAY['p_aden']::TEXT[], ARRAY['s5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_guangzhou', '广州', ARRAY['番禺', 'Guangzhou', 'Canton']::TEXT[], '中国最重要的对外贸易港口之一，海上丝绸之路的重要起点。', 'port', 'high', 113.2644, 23.1291, ARRAY['han', 'tang', 'mongol']::TEXT[], '[{"period_id":"tang","note":"设市舶司管理对外贸易，番坊有大量外商居住。"}]'::jsonb, 'confirmed', ARRAY['p_quanzhou', 'p_malacca']::TEXT[], ARRAY['s4', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_quanzhou', '泉州', ARRAY['刺桐', 'Zaiton', 'Quanzhou']::TEXT[], '宋元时期东方第一大港，被马可波罗誉为世界最大的港口之一。', 'port', 'high', 118.6758, 24.8739, ARRAY['tang', 'mongol']::TEXT[], '[{"period_id":"mongol","note":"元代极度繁荣，各国商船汇聚于此。"}]'::jsonb, 'confirmed', ARRAY['p_guangzhou', 'p_ningbo', 'p_malacca']::TEXT[], ARRAY['s3', 's4', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_ningbo', '宁波', ARRAY['明州', 'Ningbo']::TEXT[], '中国重要的港口城市，通往日本和高丽的主要港口。', 'port', 'medium', 121.5439, 29.8683, ARRAY['tang', 'mongol']::TEXT[], '[{"period_id":"tang","note":"遣唐使多在明州登陆。"}]'::jsonb, 'confirmed', ARRAY['p_quanzhou', 'p_hangzhou']::TEXT[], ARRAY[]::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO places (id, name, aliases, description, type, importance, longitude, latitude, periods, period_notes, certainty, related_place_ids, source_ids) VALUES ('p_hangzhou', '杭州', ARRAY['临安', 'Hangzhou', 'Kinsay']::TEXT[], '南宋都城，大运河的南端起点，物产丰饶。', 'capital', 'high', 120.1551, 30.2741, ARRAY['tang', 'mongol']::TEXT[], '[{"period_id":"mongol","note":"马可波罗惊叹其为‘世界上最美丽华贵之天城’。"}]'::jsonb, 'confirmed', ARRAY['p_changan', 'p_ningbo']::TEXT[], ARRAY['s3']::TEXT[]) ON CONFLICT (id) DO NOTHING;

-- Insert Routes
INSERT INTO routes (id, name, type, periods, description, coordinates, source_ids) VALUES ('r_land_main', '陆上丝绸之路主干道', 'land', ARRAY['han', 'tang', 'mongol']::TEXT[], '从长安出发，经河西走廊，跨越葱岭到达中亚和欧洲。', '[[108.9398,34.3416],[94.6618,40.1421],[89.1841,42.9476],[82.9664,41.7196],[75.9897,39.4677],[66.9749,39.6542],[62.1833,37.6667],[44.3661,33.3152],[36.2913,33.5138],[36.1601,36.2023],[28.9784,41.0082],[12.4964,41.9028]]'::jsonb, ARRAY['s1', 's2']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, type, periods, description, coordinates, source_ids) VALUES ('r_land_south', '陆上丝路南道', 'land', ARRAY['han', 'tang']::TEXT[], '绕过塔克拉玛干沙漠南缘。', '[[94.6618,40.1421],[89.9142,40.5186],[79.9222,37.1122],[75.9897,39.4677]]'::jsonb, ARRAY['s1']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO routes (id, name, type, periods, description, coordinates, source_ids) VALUES ('r_sea_main', '海上丝绸之路主干道', 'sea', ARRAY['tang', 'mongol']::TEXT[], '从中国东南沿海出发，经南中国海、印度洋，直达波斯湾和红海。', '[[121.5439,29.8683],[118.6758,24.8739],[113.2644,23.1291],[102.2501,2.1896],[75.7804,11.2588],[56.4608,27.0603],[44.9782,12.8023],[29.9187,31.2001]]'::jsonb, ARRAY['s3', 's4', 's5']::TEXT[]) ON CONFLICT (id) DO NOTHING;
